<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <joint name="camera_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="camera_link"/>
        <origin xyz="${box_x + cam_x} 0 ${box_z + cam_z}" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${cam_dx} ${cam_dy} ${cam_dz}"/>
            </geometry>
            <origin xyz="${cam_dx/2} 0 ${cam_dz/2}" />
            <material name="orange" />
        </visual>

        <collision>
            <geometry>
                <box size="${cam_dx} ${cam_dy} ${cam_dz}"/>
            </geometry>
            <origin xyz="${cam_dx/2} 0 ${cam_dz/2}" />
        </collision>

        <xacro:inertial_box mass="${cam_mass}" x="${cam_dx}" y="${cam_dy}" z="${cam_dz}">
            <origin xyz="${cam_dx/2} 0 ${cam_dz/2}" rpy="0 0 0" />
        </xacro:inertial_box>

    </link>

    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>

    <link name="camera_link_optical"></link>

    <gazebo reference="camera_link">
        
        <material>Gazebo/Orange</material>

        <sensor name="camera" type="camera">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize> true </visualize> 
            <update_rate>10</update_rate>
            <camera>
                <horizontal_fov>1.086</horizontal_fov> <!-- 62.2deg PiCamera-->
                <image>
                    <format>R8G8B8</format>
                    <width>640</width>
                    <height>480</height>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>8.0</far>
                </clip>
            </camera>

            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>camera_link_optical</frame_name>
            </plugin>
        </sensor>
    
    </gazebo>

</robot>